import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/navigationBar";
import { StrictMode } from "react";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StrictMode>
      <html lang="en">
        <title> Auradrive Resorts - VoyageAI</title>
        <Providers>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <NavigationBar />
            {children}
          </body>
        </Providers>
      </html>
    </StrictMode>
  );
}
